name: GitHub Actions to Publish docker image 
run-name: ${{ github.actor }} in Action 🚀
on: 
    push :
        branches:
            - main
jobs:
  Build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build and Tag docker image
        run : | 
            docker build -t ${{secrets.USERNAME}}/uas-pcc-rafliardiansyah-2024:latest -f Dockerfile .

      - name: Push to Dockerhub
        run: docker login -u ${{secrets.USERNAME}} -p ${{secrets.ACCESS_TOKEN}} && docker push ${{secrets.USERNAME}}/uas-pcc-rafliardiansyah-2024:latest